"""
stock_universe.py — a curated list of common NSE-listed companies,
used to power the searchable dropdown when adding a holding.

This is NOT exhaustive. It's meant to cover what most people will
type first (Nifty 50 + other well-known names) so the dropdown filters
instantly with zero network calls. Anything not in this list can still
be added via the live search (Yahoo Finance) fallback in the UI.

Each entry: (ticker, company_name)
"""

NSE_STOCKS = [
    ("RELIANCE.NS", "Reliance Industries"),
    ("TCS.NS", "Tata Consultancy Services"),
    ("HDFCBANK.NS", "HDFC Bank"),
    ("ICICIBANK.NS", "ICICI Bank"),
    ("INFY.NS", "Infosys"),
    ("BHARTIARTL.NS", "Bharti Airtel"),
    ("SBIN.NS", "State Bank of India"),
    ("LICI.NS", "Life Insurance Corporation of India"),
    ("HINDUNILVR.NS", "Hindustan Unilever"),
    ("ITC.NS", "ITC"),
    ("LT.NS", "Larsen & Toubro"),
    ("BAJFINANCE.NS", "Bajaj Finance"),
    ("HCLTECH.NS", "HCL Technologies"),
    ("MARUTI.NS", "Maruti Suzuki India"),
    ("SUNPHARMA.NS", "Sun Pharmaceutical Industries"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank"),
    ("AXISBANK.NS", "Axis Bank"),
    ("ADANIENT.NS", "Adani Enterprises"),
    ("ADANIPORTS.NS", "Adani Ports and SEZ"),
    ("ULTRACEMCO.NS", "UltraTech Cement"),
    ("TITAN.NS", "Titan Company"),
    ("ASIANPAINT.NS", "Asian Paints"),
    ("BAJAJFINSV.NS", "Bajaj Finserv"),
    ("WIPRO.NS", "Wipro"),
    ("NESTLEIND.NS", "Nestle India"),
    ("ONGC.NS", "Oil and Natural Gas Corporation"),
    ("NTPC.NS", "NTPC"),
    ("POWERGRID.NS", "Power Grid Corporation of India"),
    ("M&M.NS", "Mahindra & Mahindra"),
    ("TATAMOTORS.NS", "Tata Motors"),
    ("TATASTEEL.NS", "Tata Steel"),
    ("JSWSTEEL.NS", "JSW Steel"),
    ("COALINDIA.NS", "Coal India"),
    ("HINDALCO.NS", "Hindalco Industries"),
    ("INDUSINDBK.NS", "IndusInd Bank"),
    ("TECHM.NS", "Tech Mahindra"),
    ("GRASIM.NS", "Grasim Industries"),
    ("DRREDDY.NS", "Dr. Reddy's Laboratories"),
    ("CIPLA.NS", "Cipla"),
    ("DIVISLAB.NS", "Divi's Laboratories"),
    ("EICHERMOT.NS", "Eicher Motors"),
    ("BAJAJ-AUTO.NS", "Bajaj Auto"),
    ("HEROMOTOCO.NS", "Hero MotoCorp"),
    ("BRITANNIA.NS", "Britannia Industries"),
    ("APOLLOHOSP.NS", "Apollo Hospitals Enterprise"),
    ("SBILIFE.NS", "SBI Life Insurance"),
    ("HDFCLIFE.NS", "HDFC Life Insurance"),
    ("BPCL.NS", "Bharat Petroleum Corporation"),
    ("SHREECEM.NS", "Shree Cement"),
    ("UPL.NS", "UPL"),
    ("TATACONSUM.NS", "Tata Consumer Products"),
    ("PIDILITIND.NS", "Pidilite Industries"),
    ("DABUR.NS", "Dabur India"),
    ("GODREJCP.NS", "Godrej Consumer Products"),
    ("MARICO.NS", "Marico"),
    ("COLPAL.NS", "Colgate-Palmolive India"),
    ("HAVELLS.NS", "Havells India"),
    ("SIEMENS.NS", "Siemens"),
    ("ABB.NS", "ABB India"),
    ("BEL.NS", "Bharat Electronics"),
    ("HAL.NS", "Hindustan Aeronautics"),
    ("BOSCHLTD.NS", "Bosch"),
    ("PNB.NS", "Punjab National Bank"),
    ("BANKBARODA.NS", "Bank of Baroda"),
    ("CANBK.NS", "Canara Bank"),
    ("IDFCFIRSTB.NS", "IDFC First Bank"),
    ("FEDERALBNK.NS", "Federal Bank"),
    ("AUBANK.NS", "AU Small Finance Bank"),
    ("PFC.NS", "Power Finance Corporation"),
    ("RECLTD.NS", "REC Limited"),
    ("IRFC.NS", "Indian Railway Finance Corporation"),
    ("ZOMATO.NS", "Eternal (Zomato)"),
    ("NYKAA.NS", "FSN E-Commerce (Nykaa)"),
    ("PAYTM.NS", "One97 Communications (Paytm)"),
    ("POLICYBZR.NS", "PB Fintech (Policybazaar)"),
    ("IRCTC.NS", "Indian Railway Catering & Tourism"),
    ("DMART.NS", "Avenue Supermarts (DMart)"),
    ("TRENT.NS", "Trent"),
    ("PAGEIND.NS", "Page Industries"),
    ("VBL.NS", "Varun Beverages"),
    ("JUBLFOOD.NS", "Jubilant FoodWorks"),
    ("VOLTAS.NS", "Voltas"),
    ("PERSISTENT.NS", "Persistent Systems"),
    ("LTIM.NS", "LTIMindtree"),
    ("MPHASIS.NS", "Mphasis"),
    ("COFORGE.NS", "Coforge"),
    ("NAUKRI.NS", "Info Edge (Naukri)"),
    ("MCDOWELL-N.NS", "United Spirits"),
    ("UBL.NS", "United Breweries"),
    ("GAIL.NS", "GAIL India"),
    ("IOC.NS", "Indian Oil Corporation"),
    ("VEDL.NS", "Vedanta"),
    ("SAIL.NS", "Steel Authority of India"),
    ("NMDC.NS", "NMDC"),
    ("AMBUJACEM.NS", "Ambuja Cements"),
    ("ACC.NS", "ACC"),
    ("DLF.NS", "DLF"),
    ("GODREJPROP.NS", "Godrej Properties"),
    ("OBEROIRLTY.NS", "Oberoi Realty"),
    ("LODHA.NS", "Macrotech Developers (Lodha)"),
    ("INDIGO.NS", "InterGlobe Aviation (IndiGo)"),
    ("ADANIGREEN.NS", "Adani Green Energy"),
    ("ADANIPOWER.NS", "Adani Power"),
    ("TATAPOWER.NS", "Tata Power"),
    ("ZYDUSLIFE.NS", "Zydus Lifesciences"),
    ("LUPIN.NS", "Lupin"),
    ("AUROPHARMA.NS", "Aurobindo Pharma"),
    ("BIOCON.NS", "Biocon"),
    ("ASHOKLEY.NS", "Ashok Leyland"),
    ("TVSMOTOR.NS", "TVS Motor Company"),
    ("BALKRISIND.NS", "Balkrishna Industries"),
    ("MRF.NS", "MRF"),
    ("EXIDEIND.NS", "Exide Industries"),
    ("CUMMINSIND.NS", "Cummins India"),
    ("SRF.NS", "SRF"),
    ("PIIND.NS", "PI Industries"),
    ("DEEPAKNTR.NS", "Deepak Nitrite"),
    ("ICICIPRULI.NS", "ICICI Prudential Life Insurance"),
    ("ICICIGI.NS", "ICICI Lombard General Insurance"),
    ("MUTHOOTFIN.NS", "Muthoot Finance"),
    ("CHOLAFIN.NS", "Cholamandalam Investment & Finance"),
    ("BAJAJHLDNG.NS", "Bajaj Holdings & Investment"),
    ("LTTS.NS", "L&T Technology Services"),
    ("KPITTECH.NS", "KPIT Technologies"),
    ("TATAELXSI.NS", "Tata Elxsi"),
    ("CDSL.NS", "Central Depository Services"),
    ("BSE.NS", "BSE Limited"),
    ("MCX.NS", "Multi Commodity Exchange of India"),
    ("IEX.NS", "Indian Energy Exchange"),
    ("CAMS.NS", "Computer Age Management Services"),
]